### ISSUE TITLE
bower.json not found (macOS).

### ISSUE THREAD

**Issue by ravern** [FrigoEU/psc-ide-vim#37]
I created a new project via `pulp init` and then ran `vim src/Main.purs'. I wrote the file via `<C-W>` and it gave the error message
```
Your project is not setup correctly. Your project is missing a bower.json or psc-package.json file                                                                                       
No psc-package.json or bower.json found, couldn't start psc-ide-server
```
That's it. It was a fresh `pulp init` with a bower.json obviously in the same directory as where i started vim.

The following image shows the project layout when i ran `:find .` in vim.
<img width="1100" alt="screen shot 2017-03-21 at 12 02 59 am" src="https://cloud.githubusercontent.com/assets/22592318/24108833/c9c02a86-0dc9-11e7-9ceb-0b3730f4feac.png">

**Comment by FrigoEU** [comment]
Fixed in 0.6.3 (commit 4a69935). The mysteries of vimscript :)! Thanks for the report!

**Comment by FrigoEU** [comment]
Btw: The problem was the wrong error message was returned. The problem is that the output/ dir is not present, so you need to run pulp build first. I fixed the error messages code.

**Comment by ravern** [comment]
The issue is still present. Nothing has changed. Which directory should my vim be in?

**Comment by ravern** [comment]
Could it be my vim version? (8.0)

**Comment by FrigoEU** [comment]
Did you try running pulp build and then trying again? Is it the same problem? Are you on 0.6.3? I'm testing with neovim, if needed I'll upgrade my vim to v8.

**Comment by ravern** [comment]
Yes, the exact same problem occured.

I just deleted the plugin line from my vimrc (I am using vundle), cleaned my plugin folder and then reinstalled the plugin. I checked the source files and it should be the correct version.

I am using Vim 8.0 installed from Homebrew

**Comment by ravern** [comment]
Hi, any chance I could get in touch with you, perhaps over Discord/Gitter or other chats? I really want to use PureScript in my Vim but this Plugin still isn't working for me.

**Comment by FrigoEU** [comment]
I tried to simulate this by making a new repo with pulp and checking it in both neovim and vim 8 and I can't seem to recreate this. I'm on Gitter this evening.

**Comment by FrigoEU** [comment]
Could you run ```:find .``` again after running pulp build, and also run ```:echo expand("%:p:h")```?

**Comment by ravern** [comment]
`:find .`
<img width="2032" alt="screen shot 2017-03-30 at 8 45 53 am" src="https://cloud.githubusercontent.com/assets/22592318/24482616/573a5a82-1525-11e7-99e9-54fd8ce539da.png">

`:echo expand("%:p:h")`
<img width="399" alt="screen shot 2017-03-30 at 8 46 46 am" src="https://cloud.githubusercontent.com/assets/22592318/24482635/741527f4-1525-11e7-9708-0c9d08fe1754.png">

I have messaged you on Gitter

**Comment by FrigoEU** [comment]
Phew, found it! It's because the folder you made has a space in it. Somehow vim (or our psc-ide-vim code) isn't handling that well.

**Comment by FrigoEU** [comment]
Hey @coot ,

You added this line ```findfile("bower.json", expand("%:p:h").";")```. When I replace 
```expand("%:p:h").";"```with ```".;"``` it seems to still work, and also picks up files in folders that have spaces in them, but I can't really estimate the impact of this change. Why did you originally add that expand statement?

**Comment by ravern** [comment]
Thanks so much, it works now.

**Comment by coot** [comment]
ach, ok this will work:
```
findfile("bower.json", fnameescape(expand("%:p:h")) . ";")
```

I will make a pr.

**Comment by coot** [comment]
If you use just "." vim will start the search from the current directory and that may differ from the current path, especially if one does not set `autochdir` option.
